### PR TITLE
added support for py 3.9 and 3.10

### PR DESCRIPTION
**Pull request by itsdeka**
### Description:
At the moment this library does not work with Python >= 3.9.
This PR fixes this but may cause other side effects. Please review carefully.

### Breaking changes:
- [ ]

### New features:
- [ ]

### Fixes:
- [X]

### PR status:
- [X] Version bumped
- [X] Change-log updated

### CODE REVIEW

**Comment by itsdeka** [comment]
@vigan-abd

**Comment by itsdeka** [comment]
Not ready yet
https://github.com/bitfinexcom/bitfinex-api-py/issues/176#issuecomment-977977271

**Comment by itsdeka** [comment]
Ok, this is another approach I think will work.

**Comment by itsdeka** [comment]
https://github.com/bitfinexcom/bitfinex-api-py/issues/176#issuecomment-980544038

Fixed also pyee issue 'Error must derive from BaseException'

**Comment by itsdeka** [comment]
https://github.com/bitfinexcom/bitfinex-api-py/issues/176#issuecomment-980544038

Fixed also pyee issue 'Error must derive from BaseException'

**Review by vigan-abd — APPROVED** [review]
lgtm

**Pull request merged**
