### PR TITLE
fix: delete get_seed_trades.py

### PR DESCRIPTION
**Pull request by fintzd**
### Description:
~~Deleted~~ Moved the get_seed_trades.py file.

It was in the examples folder of the WS api, but it uses the REST method, so it is not the proper place for it.

The request here is made with REST not WS, so it is not the correct place for this example.

### Breaking changes:
- [ ]

### New features:
- Moved the file from the ws examples folder to rest examples.

### Fixes:
- [X]

### PR status:
- [ ] Version bumped
- [ ] Change-log updated

### CODE REVIEW

**Comment by itsdeka** [comment]
Hey @fintzd, could you move it in the right folder instead of deleting it?

**Review by fintzd — COMMENTED** [review]
Like this? :) @itsdeka

**Comment by itsdeka** [comment]
Great, thanks

**Review by fintzd — COMMENTED** [review]
Good right?

**Comment by robertkowalski** [comment]
thanks, merged!

**Comment by fintzd** [comment]
Cheers, thanks @robertkowalski !

**Pull request merged**
