### PR TITLE
feat: implement funding trades endpoint (rest)

### PR DESCRIPTION
**Pull request by RichardHoekstra**
### Description:
Adds [funding trades](https://docs.bitfinex.com/reference#rest-auth-funding-trades-hist) endpoint

### Breaking changes:
None

### New features:
Funding trades is available for the REST API. 

### Fixes:
None

### PR status:
- [x] Version bumped
- [x] Change-log updated

### CODE REVIEW

**Comment by itsdeka** [comment]
Looks good

@robertkowalski

**Comment by itsdeka** [comment]
Hello @RichardHoekstra, thank you very much for this PR.
Could you please add the final newline to funding_trade.py?

bfxapi/models/funding_trade.py:59:0: C0304: Final newline missing (missing-final-newline)

**Comment by itsdeka** [comment]
That was fast. Thank you again.
Looks good @robertkowalski

**Comment by RichardHoekstra** [comment]
No problem. Thanks for maintaining this project.

**Comment by itsdeka** [comment]
I noticed the last field 'maker' is not working. I have asked to update the docs.
For regular trades, the maker/taker distinction determines the fee. For funding, however, the fee is always 15% on the funding earnings, maker and taker doesn't matter.

Can you please remove the maker field from the model and consider the last field of the array a placeholder?

**Comment by RichardHoekstra** [comment]
Will get to it later today. Do you have an example of a class where a field is considered a placeholder? Not quite sure what that is going to look like.

**Comment by itsdeka** [comment]
Remove this line

https://github.com/bitfinexcom/bitfinex-api-py/pull/135/files#diff-dc038fd48665bbb0b848771668baac45bc9728be127d697d3ee8f29df43b6c7dR16

Remove this line

https://github.com/bitfinexcom/bitfinex-api-py/pull/135/files#diff-dc038fd48665bbb0b848771668baac45bc9728be127d697d3ee8f29df43b6c7dR38

Remove this line

https://github.com/bitfinexcom/bitfinex-api-py/pull/135/files#diff-dc038fd48665bbb0b848771668baac45bc9728be127d697d3ee8f29df43b6c7dR54

Remove maker from this line

https://github.com/bitfinexcom/bitfinex-api-py/pull/135/files#diff-dc038fd48665bbb0b848771668baac45bc9728be127d697d3ee8f29df43b6c7dR59

And it is ok

**Review by fintzd — APPROVED** [review]

**Comment by robertkowalski** [comment]
merged, many thanks!

**Pull request merged**
